### ISSUE TITLE
Installation fails on Centos

### ISSUE THREAD

**Issue by melezhik** [vrurg/raku-Concurrent-PChannel#1]
Hi Vadim!

RakuDist build fails on Centos:

http://repo.westus.cloudapp.azure.com/sparky/report/centos/622

```
05:01:52 05/09/2020 [bash: zef install Concurrent::PChannel] ===> Testing: Concurrent::PChannel:ver<0.0.2>:auth<github:vrurg>
05:01:57 05/09/2020 [bash: zef install Concurrent::PChannel] stderr: Aborting due to test failure: Concurrent::PChannel:ver<0.0.2>:auth<github:vrurg> (use --force-test to override)
05:01:57 05/09/2020 [bash: zef install Concurrent::PChannel] [Concurrent::PChannel] An operation first awaited:
05:01:57 05/09/2020 [bash: zef install Concurrent::PChannel] [Concurrent::PChannel]   in block <unit> at t/10-robustness.t line 89
05:01:57 05/09/2020 [bash: zef install Concurrent::PChannel] [Concurrent::PChannel] Died with the exception:
05:01:57 05/09/2020 [bash: zef install Concurrent::PChannel] [Concurrent::PChannel]     Type check failed in binding; expected Rat but got Num (1589000557.6734354e0)
05:01:57 05/09/2020 [bash: zef install Concurrent::PChannel] [Concurrent::PChannel]       in block  at t/10-robustness.t line 82
05:01:57 05/09/2020 [bash: zef install Concurrent::PChannel] ===> Testing [FAIL]: Concurrent::PChannel:ver<0.0.2>:auth<github:vrurg>
```

On other platforms (debian, ubuntu, alpine) install succeeds.

HTH

Alexey

HTH

**Comment by vrurg** [comment]
That looks like a Rakudo bug, actually. Here is the failed line:

```
        my $et = now;
```

Hence, the only place where the exception could've been risen is the core itself.

**Comment by melezhik** [comment]
Whi it is platform dependent then? The same build works fine on Debian and
Ubuntu. You can check with RakuDist.

**Comment by melezhik** [comment]
http://repo.westus.cloudapp.azure.com/sparky/report/debian/662

**Comment by vrurg** [comment]
No idea. I'm installing a centos vm, perhaps this would help. But you could see it on your own, there is no type check to fail. Perhaps `--ll-exception` would tell more about the source of the problem.

**Comment by melezhik** [comment]
I agree. It _could be_ a rakudo bug, the test on centos, against **46648b9b321c9c2c8d11a75a380a86aa1afcd636** Rakudo version succeeds.

http://repo.westus.cloudapp.azure.com/sparky/report/centos/667

**Comment by vrurg** [comment]
Could be a flapper of some kind. I gave a try to 2020.01, as in RakuDist logs and everything went smoothly.

Closing for now.

Thanks for the alarm anyway! Better a false alarm than a problem missed.
